### PR TITLE
Handle tractive off event

### LINKED ISSUE #43: Move to tractive off state when high voltage is off
https://viewer.diagrams.net/?page-id=BhlIVNj5Ru_8s9wX0_BA&highlight=0000ff&edit=_blank&layers=1&nav=1&hide-pages=1#G1uKblakAovlpPvJciPE8IRBLEZo3NYH4g

The BMS will be sending a TSAL bit over CAN to the VCU. The job of sending that information is left to the CAN team.

Create a new event in eCarEvents and implement the necessary logic in the VCU state machine according to the diagram linked above.

Prerequisites:
TSAL -> Tractive System Active Light 

Refer to here: https://docs.google.com/document/d/1Ut_q42FNuqnMAqmwgvhiAlQ1F1jr7UJEptP9l4vzhDA/edit

eCarEvents: the events of the state machine

Relevant VCU files:

vcu_common.h has eCarEvents
state_machine.c has the state machine

Not relevant for now:
You may add to the [command list](https://github.com/sfuphantom/vcu-fw/blob/75cedb33bb1e8c02da3b148fc5e2a9a2065334d3/VCU/Phantom/Drivers/UART/Phantom_sci.c#L23) to inject the event for testing

### PR DESCRIPTION
**Pull request by rafguevara14**
See #43

### CODE REVIEW

**Comment by rafguevara14** [comment]
The code works! We just had to use the function with FromISR. This holds special code to deal with critical sections when in interrupt mode. Without it, the scheduler (FreeRTOS) could unsafely interact with the processor and hang or reset the microcontroller.

Commit change: https://github.com/sfuphantom/vcu-fw/pull/68/commits/6e39d9d6f5787a49791ffd605466c37f5085c7e2

**Review by juliannesoriano20 — APPROVED** [review]

**Comment by kevinl03** [comment]
Regarding https://github.com/sfuphantom/vcu-fw/commit/6e39d9d6f5787a49791ffd605466c37f5085c7e2

Did you encounter a time when the ISR would unsafely interact with the processor, or is this simply a safety precaution you are putting in place?

**Comment by rafguevara14** [comment]
> Regarding [6e39d9d](https://github.com/sfuphantom/vcu-fw/commit/6e39d9d6f5787a49791ffd605466c37f5085c7e2)
> 
> Did you encounter a time when the ISR would unsafely interact with the processor, or is this simply a safety precaution you are putting in place?

Yes, and FreeRTOS requires that we use the FromISR functions

**Comment by kevinl03** [comment]
> > Regarding [6e39d9d](https://github.com/sfuphantom/vcu-fw/commit/6e39d9d6f5787a49791ffd605466c37f5085c7e2)
> > Did you encounter a time when the ISR would unsafely interact with the processor, or is this simply a safety precaution you are putting in place?
> 
> Yes, and FreeRTOS requires that we use the FromISR functions

Why was this overlooked in the initial implementation. Having the second NotifyStateMachine might not be necessary?

**Comment by rafguevara14** [comment]
> > > Regarding [6e39d9d](https://github.com/sfuphantom/vcu-fw/commit/6e39d9d6f5787a49791ffd605466c37f5085c7e2)
> > > Did you encounter a time when the ISR would unsafely interact with the processor, or is this simply a safety precaution you are putting in place?
> > 
> > 
> > Yes, and FreeRTOS requires that we use the FromISR functions
> 
> Why was this overlooked in the initial implementation. Having the second NotifyStateMachine might not be necessary?

Not sure what you mean. The code was WIP so that commit was made just a few hours later after I got home and noticed I was calling the wrong function.

If by the second NotifyStateMachine you mean having functions NotifyStateMachine and NotifyStateMachineISR rather than just one function, it's because these functions are just wrappers for the FreeRTOS API. It wasn't intended to add extra logic to determine the execution context (calling code is from a task vs from an ISR).

These scenarios are very common in embedded systems and even moreso in FreeRTOS. Check this section if it's still unclear.
[7.2 Using the FreeRTOS API from an ISR](https://github.com/FreeRTOS/FreeRTOS-Kernel-Book/blob/main/ch07.md#72-using-the-freertos-api-from-an-isr)

**Comment by kevinl03** [comment]
> > > > Regarding [6e39d9d](https://github.com/sfuphantom/vcu-fw/commit/6e39d9d6f5787a49791ffd605466c37f5085c7e2)
> > > > Did you encounter a time when the ISR would unsafely interact with the processor, or is this simply a safety precaution you are putting in place?
> > > 
> > > 
> > > Yes, and FreeRTOS requires that we use the FromISR functions
> > 
> > 
> > Why was this overlooked in the initial implementation. Having the second NotifyStateMachine might not be necessary?
> 
> Not sure what you mean. The code was WIP so that commit was made just a few hours later after I got home and noticed I was calling the wrong function.
> 
> If by the second NotifyStateMachine you mean having functions NotifyStateMachine and NotifyStateMachineISR rather than just one function, it's because these functions are just wrappers for the FreeRTOS API. It wasn't intended to add extra logic to determine the execution context (calling code is from a task vs from an ISR).
> 
> These scenarios are very common in embedded systems and even moreso in FreeRTOS. Check this section if it's still unclear. [7.2 Using the FreeRTOS API from an ISR](https://github.com/FreeRTOS/FreeRTOS-Kernel-Book/blob/main/ch07.md#72-using-the-freertos-api-from-an-isr)

Right, and how are we certain that that NotifyStateMachineFromISR is actually getting called from an ISR and not from another source?

**Comment by rafguevara14** [comment]
> > > > > Regarding [6e39d9d](https://github.com/sfuphantom/vcu-fw/commit/6e39d9d6f5787a49791ffd605466c37f5085c7e2)
> > > > > Did you encounter a time when the ISR would unsafely interact with the processor, or is this simply a safety precaution you are putting in place?
> > > > 
> > > > 
> > > > Yes, and FreeRTOS requires that we use the FromISR functions
> > > 
> > > 
> > > Why was this overlooked in the initial implementation. Having the second NotifyStateMachine might not be necessary?
> > 
> > 
> > Not sure what you mean. The code was WIP so that commit was made just a few hours later after I got home and noticed I was calling the wrong function.
> > If by the second NotifyStateMachine you mean having functions NotifyStateMachine and NotifyStateMachineISR rather than just one function, it's because these functions are just wrappers for the FreeRTOS API. It wasn't intended to add extra logic to determine the execution context (calling code is from a task vs from an ISR).
> > These scenarios are very common in embedded systems and even moreso in FreeRTOS. Check this section if it's still unclear. [7.2 Using the FreeRTOS API from an ISR](https://github.com/FreeRTOS/FreeRTOS-Kernel-Book/blob/main/ch07.md#72-using-the-freertos-api-from-an-isr)
> 
> Right, and how are we certain that that NotifyStateMachineFromISR is actually getting called from an ISR and not from another source?

Currently that is the responsibility of the application programmer when they use the function. In this case, the call is being used in a static function that is linked to a hardware interrupt. The use of NotifyStateMachineFromISR in this PR will be guranteed to be called only during an ISR because of this

**Comment by rafguevara14** [comment]
The code was validated on real hardware before I left and can be merged to develop. More testing can be done when phantom release 2 is released

**Pull request merged**
